services:
  zoraxy:
    image: zoraxydocker/zoraxy:latest
    container_name: zoraxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8000:8000
    networks:
      - homelab
    volumes:
      - /path/to/zoraxy/config/:/opt/zoraxy/config/
      - /path/to/zoraxy/plugin/:/opt/zoraxy/plugin/
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      FASTGEOIP: "true"
  tailscale:
    image: tailscale/tailscale:stable
    container_name: tailscale-zoraxy
    # 💡 Sidecar: compartilha exatamente a mesma pilha de rede do Zoraxy
    network_mode: "service:zoraxy"
    depends_on:
      - zoraxy
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - tailscale-state:/var/lib/tailscale
    environment:
      # defina no arquivo .env ao lado do compose
      TS_AUTHKEY: "[[TS_AUTHKEY]]"
    command: >
      sh -c "
        tailscaled --state=/var/lib/tailscale/tailscaled.state &
        sleep 2 &&
        tailscale up
          --authkey=[[TS_AUTHKEY]]
          --hostname=zoraxy-sidecar
          --accept-routes=true
          --accept-dns=false
        &&
        tail -f /dev/null
      "
    restart: unless-stopped

volumes:
  tailscale-state:
    driver: local

networks:
      homelab:
        external: true